version: '3'
services:
  spire-server:
    image: tjamir/spire-server:demo
    hostname: spire-server
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - ./docker/conf/server:/opt/spire/conf/server
  